[package]
name = "just_text"
version = "0.1.0"
authors = ["wjl <william.lewis112358@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
handlebars = "3.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
